(setq *rarm-pos-1*
      (make-coords
       :pos #f(655 5 880)
       :rpy #f(1.529 0.0 3.13)
       ))

(setq *rarm-pos-2*
      (make-coords
       :pos #f(658.5 5 875)
       :rpy #f(1.14 0.0 3.13)
       ))

(setq *larm-pos-1*
      (make-coords
       :pos #f(660 0 1000)
       :rpy #f(-0.0 0.0 0.0)
       ))

(setq *larm-pos-2*
      (make-coords
       :pos #f(658.8 -3.5 995)
       :rpy #f(-0.39 -0.0 0.0)
       ))
